### ISSUE TITLE
Delete the random test skills from the developer portal

### ISSUE THREAD

**Issue by ezquire** [370-Alexa-Project/CS370_Echo_Demo#64]
Do we still need these?

**Comment by ezquire** [comment]
still need confirmation on deleting test skills...anyone who currently has one open in the developer portal please let me know when you are done with it so I can delete it, or if you don't need it, feel free to delete it yourself just don't touch the "Utterance Test #2" or "Sonoma State" (well obviously you don't want to delete the main skill but I need "Utterance Test #2" still).

**Comment by ghost** [comment]
I deleted Error Operator.  That was my test skill but I'll just use Utterance Test now.

**Comment by ezquire** [comment]
is jorge test even a thing? can i delete?

**Comment by ghost** [comment]
These are our test skills we use to test changes we're working on, I'm not really sure why you're so worked up about getting rid of them. I don't know if Jorge is going to use his again, but it's not hurting anyone by being there, and if he needs to test something it's a bit of a hassle to have to go through setting up a new skill again.

I'm going to close this issue since the testing skills are transient in nature and garbage collecting the orphaned ones is an ongoing task.
